.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ALCF\-COMPARE" "1" "April 2024" ""
.SH "NAME"
\fBalcf\-compare\fR \- Calculate comparison statistics from multiple lidar time series\.
.SH "SYNOPSIS"
.nf
alcf compare <input_1> <input_2> [<input_n>\|\.\|\.\|\.] <output>
.fi
.SH "ARGUMENTS"
.TP
\fBinput_*\fR
Input lidar data directory\.
.TP
\fBoutput\fR
Output filename\.
.SH "COPYRIGHT"
Copyright \(co 2019–2024 Peter Kuma, Adrian J\. McDonald, Olaf Morgenstern, Richard Querel, Israel Silber and Connor J\. Flynn\.
.SH "BUG REPORTING"
Report bugs to Peter Kuma (\fIpeter@peterkuma\.net\fR)\.
.SH "SEE ALSO"
alcf(1), alcf\-auto(1), alcf\-calibrate(1), alcf\-convert(1), alcf\-download(1), alcf\-lidar(1), alcf\-model(1), alcf\-plot(1), alcf\-simulate(1), alcf\-stats(1)
