.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ALCF\-DOWNLOAD" "1" "April 2024" ""
.SH "NAME"
\fBalcf\-download\fR \- Download model data\.
.SH "SYNOPSIS"
.nf
alcf download <type> [login_options] \-\-login
alcf download <type> point: { <lon> <lat> } time: { <start> <end> } [<options>] [\-\-] <output>
alcf download <type> track: <track> [<options>] [\-\-] <output>
.fi
.SH "DESCRIPTION"
This command downloads model data required by the lidar simulator for a given geographical point or ship track\. Not all models supported by the other ALCF commands are supported by \fBalcf download\fR \- these have to be acquired manually\. Before downloading data, you have register an account on Copernicus CDS (ERA5; https://cds\.climate\.copernicus\.eu) or NASA Earthdata (MERRA\-2; https://earthdata\.nasa\.gov) and run \fBalcf download <type> \-\-login\fR\. This prompts for credentials interactively\. For non\-interactive use, use the \fB\-\-overwrite\fR option and credential options (see the login options below)\. Only geographical subsets necessary to cover the point or track are downloaded\.
.P
Arguments following \fB\-\-\fR are treated as literal strings\. Use this delimiter if the output file name might otherwise be interpreted as non\-strings, e\.g\. purely numerical file names\.
.SH "ARGUMENTS"
.IP "\[ci]" 4
\fBtype\fR: Model type (see Model types below)\.
.IP "\[ci]" 4
\fBlon\fR: Point longitude (degrees East)\.
.IP "\[ci]" 4
\fBlat\fR: Point latitutde (degrees North)\.
.IP "\[ci]" 4
\fBstart\fR: Start time (see Time format below)\.
.IP "\[ci]" 4
\fBend\fR: End time (see Time format below)\.
.IP "\[ci]" 4
\fBtrack: <file>\fR, \fBtrack: { <file>\|\.\|\.\|\. }\fR: One or more track NetCDF files (see Files below)\. If multiple files are supplied and \fBtime_bnds\fR is not present in the files, they are assumed to be multiple segments of a discontinous track unless the last and first time of adjacent tracks are the same\.
.IP "\[ci]" 4
\fBoutput\fR: Output directory\.
.IP "\[ci]" 4
\fBlogin_options\fR: See login options below\.
.IP "\[ci]" 4
\fBoptions\fR: See Options below\.
.IP "" 0
.SH "OPTIONS"
.TP
\fB\-\-nocache\fR
Disable server\-side caching of requests, when applicable\.
.TP
\fB\-\-overwrite\fR
Overwrite existing files\.
.TP
\fBtrack_gap: <interval>\fR
If the interval is not 0, a track file is supplied, the \fBtime_bnds\fR variable is not defined in the file and any two adjacent points are separated by more than the specified time interval (seconds), then a gap is assumed to be present between the two data points, instead of interpolating location between the two points\. Default: \fB21600\fR (6 hours)\.
.SH "LOGIN OPTIONS"
.TP
\fB\-\-overwrite\fR
Overwrite existing files\.
.SH "MERRA\-2 LOGIN OPTIONS"
.TP
\fBuser: <value>\fR
Supply non\-interactive user instead of prompting\.
.TP
\fBpassword: <value>\fR
Supply non\-interactive password instead of prompting\.
.SH "ERA5 LOGIN OPTIONS"
.TP
\fBuid: <value>\fR
Supply non\-interactive UID instead of prompting\.
.TP
\fBkey: <value>\fR
Supply non\-interactive API key instead of prompting\.
.SH "MODEL TYPES"
.TP
\fBera5\fR
ERA5\.
.TP
\fBmerra2\fR
MERRA\-2\.
.SH "FILES"
The track file is a NetCDF file containing 1D variables \fBlon\fR, \fBlat\fR, \fBtime\fR, and optionally \fBtime_bnds\fR\. \fBtime\fR and \fBtime_bnds\fR are time in format conforming with the CF Conventions (has a valid \fBunits\fR attribute and optional \fBcalendar\fR attribute), \fBlon\fR is longitude between 0 and 360 degrees and \fBlat\fR is latitude between \-90 and 90 degrees\. If \fBtime_bnds\fR is provided, discontinous track segments can be specified if adjacent time bounds are not coincident\. The variables \fBlon\fR, \fBlat\fR and \fBtime\fR have a single dimension \fBtime\fR\. The variable \fBtime_bnds\fR has dimensions (\fBtime\fR, \fBbnds\fR)\.
.SH "TIME FORMAT"
\fBYYYY\-MM\-DD[THH:MM[:SS]]\fR, where \fBYYYY\fR is year, \fBMM\fR is month, \fBDD\fR is day, \fBHH\fR is hour, \fBMM\fR is minute, \fBSS\fR is second\. Example: \fB2000\-01\-01T00:00:00\fR\.
.SH "EXAMPLES"
Log in to the Copernicus CDS (ERA5) service:
.IP "" 4
.nf
alcf download era5 \-\-login
.fi
.IP "" 0
.P
Download ERA5 data at 45 S, 170 E between 1 and 2 January 2020 and store the output in the directory \fBera5\fR\.
.IP "" 4
.nf
alcf download era5 point: { \-45\.0 170\.0 } time: { 2020\-01\-01 2020\-01\-02 } era5
.fi
.IP "" 0
.P
Log in to the NASA Earthdata (MERRA\-2) service:
.IP "" 4
.nf
alcf download merra2 \-\-login
.fi
.IP "" 0
.P
Download MERRA\-2 data for a ship track \fBtrack\.nc\fR and store the output in the directory \fBmerra2\fR\.
.IP "" 4
.nf
alcf download merra2 track: track\.nc merra2
.fi
.IP "" 0
.SH "COPYRIGHT"
Copyright \(co 2019–2024 Peter Kuma, Adrian J\. McDonald, Olaf Morgenstern, Richard Querel, Israel Silber and Connor J\. Flynn\.
.SH "BUG REPORTING"
Report bugs to Peter Kuma (\fIpeter@peterkuma\.net\fR)\.
.SH "SEE ALSO"
alcf(1), alcf\-auto(1), alcf\-calibrate(1), alcf\-compare(1), alcf\-convert(1), alcf\-lidar(1), alcf\-model(1), alcf\-plot(1), alcf\-simulate(1), alcf\-stats(1)
