#!/usr/bin/env python3

import pystache
from alcf.cmds import CMDS

def get_vars():
	vars = {}
	for k, cmd in CMDS.items():
		vars['cmd_%s' % k] = cmd.__doc__
	return vars

if __name__ == '__main__':
	print('<- README.template.md')
	with open('README.template.md', 'rb') as f:
		template = f.read().decode('utf-8')
	vars = get_vars()
	output = pystache.render(template, vars)
	with open('README.md', 'wb') as f:
		f.write(output.encode('utf-8'))
		print('-> README.md')
