#!/bin/sh
mkdir -p dep
cd dep
git clone https://github.com/Unidata/netcdf-c
git clone https://github.com/Unidata/netcdf-fortran
git clone https://github.com/peterkuma/COSPv1 cosp
cd netcdf-c
git checkout v4.6.2
cd ..
cd netcdf-fortran
git checkout v4.4.5
