#!/usr/bin/env python

import pystache
from alcf.cmds import CMDS

def get_vars():
	vars = {}
	for k, cmd in CMDS.iteritems():
		vars['cmd_%s' % k] = cmd.__doc__
	return vars

if __name__ == '__main__':
	print('<- README.template.md')
	with open('README.template.md') as f:
		template = f.read()
	vars = get_vars()
	output = pystache.render(template, vars)
	with open('README.md', 'w') as f:
		f.write(output)
		print('-> README.md')
