#!/bin/sh
set -e
cd build
export CC=gcc
export FC=gfortran
prefix="$(pwd)/opt"
includedir="$prefix/include"
libdir="$prefix/lib"
export LDFLAGS="-L"$libdir""
export CFLAGS="-I$includedir"
export C_INCLUDE_PATH="$includedir"
export LIBRARY_PATH="$libdir"
export LD_LIBRARY_PATH="$libdir"
jobs=10
tar xf udunits-2.2.26.tar.gz
tar xf netcdf-v4.8.0.tar.gz
tar xf netcdf-fortran-v4.5.3.tar.gz
tar xf uuid-1.6.2.tar.gz
tar xf hdf5-1.10.4.tar.gz
tar xf cmor-2.9.1.tar.xz
unzip -o cosp-master.zip
cd uuid-1.6.2
./configure --prefix="$prefix"
make -j $jobs
make -j $jobs install
cd ..
cd hdf5-hdf5-1_10_4
 ./configure --prefix="$prefix"
make -j $jobs
make -j $jobs install
cd ..
cd udunits-2.2.26
./configure --prefix="$prefix"
make -j $jobs
make -j $jobs install
cd ..
cd netcdf-c-4.8.0
./configure --prefix="$prefix"
make -j $jobs
make -j $jobs install
cd ..
cd netcdf-fortran-4.5.3
./configure --prefix="$prefix"
make -j $jobs
make -j $jobs install
cd ..
cd cmor-2.9.1
patch < ../../cmor_patch.diff
./configure --prefix="$prefix"
make -j $jobs
make -j $jobs install
cd ..
cd COSPv1-master
patch < ../../cosp_patch.diff
make
cd ..
echo "Finished building dependencies"
