#!/bin/sh
mkdir -p build
cd build
wget -c https://github.com/HDFGroup/hdf5/archive/hdf5-1_10_4.tar.gz -O hdf5-1.10.4.tar.gz
wget -c http://deb.debian.org/debian/pool/main/u/udunits/udunits_2.2.26.orig.tar.xz -O udunits-2.2.26.tar.gz
wget -c https://github.com/Unidata/netcdf-c/archive/v4.8.0.tar.gz -O netcdf-v4.8.0.tar.gz
wget -c https://github.com/Unidata/netcdf-fortran/archive/v4.5.3.tar.gz -O netcdf-fortran-v4.5.3.tar.gz
wget -c http://deb.debian.org/debian/pool/main/o/ossp-uuid/ossp-uuid_1.6.2.orig.tar.gz -O uuid-1.6.2.tar.gz
wget -c http://deb.debian.org/debian/pool/main/c/cmor/cmor_2.9.1.orig.tar.xz -O cmor-2.9.1.tar.xz
wget -c https://github.com/alcf-lidar/COSPv1/archive/master.zip -O cosp-master.zip
echo "Finished downloading dependencies"
