#!/bin/sh
mkdir -p build
cd build
wget -c https://github.com/Unidata/netcdf-c/archive/v4.6.2.tar.gz -O netcdf-v4.6.2.tar.gz
wget -c https://github.com/Unidata/netcdf-fortran/archive/v4.4.5.tar.gz -O netcdf-fortran-v4.4.5.tar.gz
wget -c http://deb.debian.org/debian/pool/main/o/ossp-uuid/ossp-uuid_1.6.2.orig.tar.gz -O uuid-1.6.2.tar.gz
wget -c https://github.com/PCMDI/cmor/archive/3.4.0.tar.gz -O cmor-3.4.0.tar.gz
wget -c https://github.com/peterkuma/COSPv1/archive/master.zip -O cosp-master.tar.gz